pub mod audit_handler;
pub mod auth_handler;
pub mod comments_handler;
pub mod debug;
pub mod diary_handler;
pub mod health;
pub mod job_plans_handler;
pub mod marketplace_handler;
pub mod metrics;
pub mod references_handler;
pub mod roles_handler;
pub mod shifts_handler;
pub mod templates_handler;
pub mod user_roles_handler;
pub mod users_handler;
pub mod workplaces_handler;

pub use debug::debug_handler;
pub use health::health_check;
pub use metrics::{metrics_handler, setup_metrics_recorder, MetricsState};
